import 'package:get_it/get_it.dart';
import 'package:hive/hive.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:todo/data/datasources/task_local_datasource.dart';
import 'package:todo/data/repositories/task_repository_impl.dart';
import 'package:todo/domain/repositories/task_repository.dart';
import 'package:todo/domain/entities/task.dart';
import 'package:todo/presentation/bloc/task_bloc.dart';

final GetIt sl = GetIt.instance;

Future<void> init() async {
  // Initialize Hive
  await Hive.initFlutter();

  // Register the TypeAdapters (generated by hive_generator)
  if (!Hive.isAdapterRegistered(0)) {
    Hive.registerAdapter(TaskAdapter());
  }

  // ADD THIS: Register the PriorityAdapter
  if (!Hive.isAdapterRegistered(1)) {
    Hive.registerAdapter(PriorityAdapter());
  }

  // Open the Hive box
  await Hive.openBox<Task>('tasksBox');

  // Data sources
  sl.registerLazySingleton<TaskLocalDataSource>(
        () => TaskLocalDataSourceImpl(),
  );

  // Repository
  sl.registerLazySingleton<TaskRepository>(
        () => TaskRepositoryImpl(
      localDataSource: sl<TaskLocalDataSource>(),
    ),
  );

  // Bloc
  sl.registerFactory(
        () => TaskBloc(taskRepository: sl<TaskRepository>()),
  );
}